Allow custom inspection of errors
sony/gobreaker pull request #29
Opened 2020-09-29 18:34 UTC by dmarkhas

Not all errors should be counted towards tripping the circuit breaker, this PR adds support for a custom inspection strategy to determine if an error should trip the circuit breaker or not.

2020-12-02 12:56 UTC, xswordsx commented
This would be very useful for my usecase as well - Since gRPC returns errors to denote 4XX Status codes (e.g. `NotFound`) I am getting a lot of false-positives.

2020-12-28 01:54 UTC, YoshiyukiMineo commented
@dmarkhas 

Sorry for the late reply. Your idea sounds good. But I think `IsSuccessful` is more straightforward than `ShouldTrip`.

2020-12-28 12:02 UTC, dmarkhas commented
Renamed :)

2020-12-29 03:34 UTC, YoshiyukiMineo requested changes
I have added review comments.

2020-12-29 03:34 UTC, YoshiyukiMineo commented on gobreaker.go
> +	shouldTrip    func(err error) bool
shouldTrip -> isSuccessful

2020-12-29 03:34 UTC, YoshiyukiMineo commented on gobreaker.go
> +func defaultShouldTrip(err error) bool {
defaultShouldTrip -> defaultIsSuccessful

2020-12-29 03:34 UTC, YoshiyukiMineo commented on gobreaker.go
> +// IsSuccessful is called with the error returned from the request, if not nil.
Please modify the comments because IsSuccessful returns the opposite value of ShouldTrip.

2020-12-29 03:34 UTC, YoshiyukiMineo commented on gobreaker.go
> +	return err != nil
```
err == nil
```
because IsSuccessful returns the opposite value of ShouldTrip.

2020-12-29 03:34 UTC, YoshiyukiMineo commented on gobreaker.go
> +	cb.afterRequest(generation, !cb.shouldTrip(err))
```
cb.isSuccessful(err)
```
because IsSuccessful returns the opposite value of ShouldTrip.

2021-01-04 13:18 UTC, dmarkhas commented
Thanks, I've addressed your comments.

2021-01-05 10:41 UTC, YoshiyukiMineo commented
Thank you!

2021-01-05 10:42 UTC, merged

2021-01-05 13:16 UTC, xswordsx commented
Is the next version of the package coming out soon _(as I am eagerly awaiting this feature)_ ?